### ISSUE TITLE
JavascriptException: Module AppRegistry is not a registered callable module (calling runApplication), stack:

### ISSUE THREAD

**Issue by ovr** [ovr/ghubber#11]
https://sentry.io/ghubber/android/issues/280154097/

```
JavascriptException: Module AppRegistry is not a registered callable module (calling runApplication), stack:
value@22:2859
<unknown>@22:941
value@22:2401
value@22:913

    at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:99)
    at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:83)
    at java.lang.reflect.Method.invokeNative(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
...
(8 additional frame(s) were not displayed)

Module AppRegistry is not a registered callable module (calling runApplication), stack:
value@22:2859
<unknown>@22:941
value@22:2401
value@22:913

```

**Comment by ovr** [comment]
Fixed, release in `v0.4.1`
